/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

/*================ RCC =================*/
#define RCC_APB2ENR   (*(volatile uint32_t*)0x40021018)

/*================ GPIOA ================*/
#define GPIOA_CRL     (*(volatile uint32_t*)0x40010800)
#define GPIOA_CRH     (*(volatile uint32_t*)0x40010804)
#define GPIOA_BSRR    (*(volatile uint32_t*)0x40010810)
#define GPIOA_BRR     (*(volatile uint32_t*)0x40010814)

/*================ USART1 ================*/
#define USART1_SR     (*(volatile uint32_t*)0x40013800)
#define USART1_DR     (*(volatile uint32_t*)0x40013804)
#define USART1_BRR    (*(volatile uint32_t*)0x40013808)
#define USART1_CR1    (*(volatile uint32_t*)0x4001380C)

/*================ Delay =================*/
void delay_ms(uint32_t ms)
{
    for(uint32_t i=0;i<ms*8000;i++)
    {
        __asm("NOP");
    }
}

/*================ GPIO Init =================*/
void GPIO_Init(void)
{
    RCC_APB2ENR |= (1<<2);      // GPIOA Clock

    /* PA4 Output Push Pull 2MHz */
    GPIOA_CRL &= ~(0xF<<16);
    GPIOA_CRL |=  (0x2<<16);

    /* PA5 Output Push Pull 2MHz */
    GPIOA_CRL &= ~(0xF<<20);
    GPIOA_CRL |=  (0x2<<20);
}

/*================ USART1 Init =================*/
void USART1_Init(void)
{
    RCC_APB2ENR |= (1<<14);     // USART1 Clock

    /* PA9 TX */
    GPIOA_CRH &= ~(0xF<<4);
    GPIOA_CRH |=  (0xB<<4);

    /* PA10 RX */
    GPIOA_CRH &= ~(0xF<<8);
    GPIOA_CRH |=  (0x4<<8);

    /* Change this if your clock is 72 MHz */
    USART1_BRR = 0x0341;        // 9600 baud @8MHz

    USART1_CR1 |= (1<<13);      // UE
    USART1_CR1 |= (1<<3);       // TE
    USART1_CR1 |= (1<<2);       // RE
}

/*================ Receive =================*/
char USART1_Read(void)
{
    while(!(USART1_SR & (1<<5)));

    return USART1_DR;
}

/*================ Main =================*/
int main(void)
{
    GPIO_Init();
    USART1_Init();

    while(1)
    {
        char ch = USART1_Read();

        switch(ch)
        {
            case 'B':
                GPIOA_BSRR = (1<<5);      // Blue LED ON
                break;

            case 'b':
                GPIOA_BRR = (1<<5);       // Blue LED OFF
                break;

            case 'G':
                GPIOA_BSRR = (1<<4);      // Green LED ON
                break;

            case 'g':
                GPIOA_BRR = (1<<4);       // Green LED OFF
                break;

            case 'A':
                GPIOA_BSRR = (1<<4);
                GPIOA_BSRR = (1<<5);      // Both LEDs ON
                break;

            case 'a':
                GPIOA_BRR = (1<<4);
                GPIOA_BRR = (1<<5);       // Both LEDs OFF
                break;

            case 'L':                     // Blink both LEDs
                for(int i=0;i<5;i++)
                {
                    GPIOA_BSRR = (1<<4);
                    GPIOA_BSRR = (1<<5);
                    delay_ms(300);

                    GPIOA_BRR = (1<<4);
                    GPIOA_BRR = (1<<5);
                    delay_ms(300);
                }
                break;
        }
    }
}
